using System.Collections.Generic;

namespace NimatorCouchBase.CouchBase.Statistics.Bucker
{
    public class Samples
    {
        public List<int> CouchTotalDiskSize { get; set; }
        public List<int> CouchDocsFragmentation { get; set; }
        public List<int> CouchViewsFragmentation { get; set; }
        public List<int> HitRatio { get; set; }
        public List<int> EpCacheMissRate { get; set; }
        public List<int> EpResidentItemsRate { get; set; }
        public List<int> VbAvgActiveQueueAge { get; set; }
        public List<int> VbAvgReplicaQueueAge { get; set; }
        public List<int> VbAvgPendingQueueAge { get; set; }
        public List<int> VbAvgTotalQueueAge { get; set; }
        public List<int> VbActiveResidentItemsRatio { get; set; }
        public List<int> VbReplicaResidentItemsRatio { get; set; }
        public List<int> VbPendingResidentItemsRatio { get; set; }
        public List<int> AvgDiskUpdateTime { get; set; }
        public List<int> AvgDiskCommitTime { get; set; }
        public List<int> AvgBgWaitTime { get; set; }
        public List<int> AvgActiveTimestampDrift { get; set; }
        public List<int> AvgReplicaTimestampDrift { get; set; }
        public List<int> InvalidNameEpDcpViewsindexesCount { get; set; }
        public List<int> InvalidNameEpDcpViewsindexesItemsRemaining { get; set; }
        public List<int> InvalidNameEpDcpViewsindexesProducerCount { get; set; }
        public List<int> InvalidNameEpDcpViewsindexesTotalBacklogSize { get; set; }
        public List<int> InvalidNameEpDcpViewsindexesItemsSent { get; set; }
        public List<int> InvalidNameEpDcpViewsindexesTotalBytes { get; set; }
        public List<int> InvalidNameEpDcpViewsindexesBackoff { get; set; }
        public List<int> BgWaitCount { get; set; }
        public List<int> BgWaitTotal { get; set; }
        public List<double> BytesRead { get; set; }
        public List<double> BytesWritten { get; set; }
        public List<int> CasBadval { get; set; }
        public List<int> CasHits { get; set; }
        public List<int> CasMisses { get; set; }
        public List<int> CmdGet { get; set; }
        public List<int> CmdSet { get; set; }
        public List<int> CouchDocsActualDiskSize { get; set; }
        public List<int> CouchDocsDataSize { get; set; }
        public List<int> CouchDocsDiskSize { get; set; }
        public List<int> CouchSpatialDataSize { get; set; }
        public List<int> CouchSpatialDiskSize { get; set; }
        public List<int> CouchSpatialOps { get; set; }
        public List<int> CouchViewsActualDiskSize { get; set; }
        public List<int> CouchViewsDataSize { get; set; }
        public List<int> CouchViewsDiskSize { get; set; }
        public List<int> CouchViewsOps { get; set; }
        public List<int> CurrConnections { get; set; }
        public List<int> CurrItems { get; set; }
        public List<int> CurrItemsTot { get; set; }
        public List<int> DecrHits { get; set; }
        public List<int> DecrMisses { get; set; }
        public List<int> DeleteHits { get; set; }
        public List<int> DeleteMisses { get; set; }
        public List<int> DiskCommitCount { get; set; }
        public List<int> DiskCommitTotal { get; set; }
        public List<int> DiskUpdateCount { get; set; }
        public List<int> DiskUpdateTotal { get; set; }
        public List<int> DiskWriteQueue { get; set; }
        public List<int> EpActiveAheadExceptions { get; set; }
        public List<int> EpActiveHlcDrift { get; set; }
        public List<int> EpActiveHlcDriftCount { get; set; }
        public List<int> EpBgFetched { get; set; }
        public List<int> EpClockCasDriftThresholdExceeded { get; set; }
        public List<int> EpDcp_2IBackoff { get; set; }
        public List<int> EpDcp_2ICount { get; set; }
        public List<int> EpDcp_2IItemsRemaining { get; set; }
        public List<int> EpDcp_2IItemsSent { get; set; }
        public List<int> EpDcp_2IProducerCount { get; set; }
        public List<int> EpDcp_2ITotalBacklogSize { get; set; }
        public List<int> EpDcp_2ITotalBytes { get; set; }
        public List<int> EpDcpFtsBackoff { get; set; }
        public List<int> EpDcpFtsCount { get; set; }
        public List<int> EpDcpFtsItemsRemaining { get; set; }
        public List<int> EpDcpFtsItemsSent { get; set; }
        public List<int> EpDcpFtsProducerCount { get; set; }
        public List<int> EpDcpFtsTotalBacklogSize { get; set; }
        public List<int> EpDcpFtsTotalBytes { get; set; }
        public List<int> EpDcpOtherBackoff { get; set; }
        public List<int> EpDcpOtherCount { get; set; }
        public List<int> EpDcpOtherItemsRemaining { get; set; }
        public List<int> EpDcpOtherItemsSent { get; set; }
        public List<int> EpDcpOtherProducerCount { get; set; }
        public List<int> EpDcpOtherTotalBacklogSize { get; set; }
        public List<int> EpDcpOtherTotalBytes { get; set; }
        public List<int> EpDcpReplicaBackoff { get; set; }
        public List<int> EpDcpReplicaCount { get; set; }
        public List<int> EpDcpReplicaItemsRemaining { get; set; }
        public List<int> EpDcpReplicaItemsSent { get; set; }
        public List<int> EpDcpReplicaProducerCount { get; set; }
        public List<int> EpDcpReplicaTotalBacklogSize { get; set; }
        public List<int> EpDcpReplicaTotalBytes { get; set; }
        public List<int> EpDcpViewsBackoff { get; set; }
        public List<int> EpDcpViewsCount { get; set; }
        public List<int> EpDcpViewsItemsRemaining { get; set; }
        public List<int> EpDcpViewsItemsSent { get; set; }
        public List<int> EpDcpViewsProducerCount { get; set; }
        public List<int> EpDcpViewsTotalBacklogSize { get; set; }
        public List<int> EpDcpViewsTotalBytes { get; set; }
        public List<int> EpDcpXdcrBackoff { get; set; }
        public List<int> EpDcpXdcrCount { get; set; }
        public List<int> EpDcpXdcrItemsRemaining { get; set; }
        public List<int> EpDcpXdcrItemsSent { get; set; }
        public List<int> EpDcpXdcrProducerCount { get; set; }
        public List<int> EpDcpXdcrTotalBacklogSize { get; set; }
        public List<int> EpDcpXdcrTotalBytes { get; set; }
        public List<int> EpDiskqueueDrain { get; set; }
        public List<int> EpDiskqueueFill { get; set; }
        public List<int> EpDiskqueueItems { get; set; }
        public List<int> EpFlusherTodo { get; set; }
        public List<int> EpItemCommitFailed { get; set; }
        public List<int> EpKvSize { get; set; }
        public List<object> EpMaxSize { get; set; }
        public List<object> EpMemHighWat { get; set; }
        public List<object> EpMemLowWat { get; set; }
        public List<int> EpMetaDataMemory { get; set; }
        public List<int> EpNumNonResident { get; set; }
        public List<int> EpNumOpsDelMeta { get; set; }
        public List<int> EpNumOpsDelRetMeta { get; set; }
        public List<int> EpNumOpsGetMeta { get; set; }
        public List<int> EpNumOpsSetMeta { get; set; }
        public List<int> EpNumOpsSetRetMeta { get; set; }
        public List<int> EpNumValueEjects { get; set; }
        public List<int> EpOomErrors { get; set; }
        public List<int> EpOpsCreate { get; set; }
        public List<int> EpOpsUpdate { get; set; }
        public List<int> EpOverhead { get; set; }
        public List<int> EpQueueSize { get; set; }
        public List<int> EpReplicaAheadExceptions { get; set; }
        public List<int> EpReplicaHlcDrift { get; set; }
        public List<int> EpReplicaHlcDriftCount { get; set; }
        public List<int> EpTmpOomErrors { get; set; }
        public List<int> EpVbTotal { get; set; }
        public List<int> Evictions { get; set; }
        public List<int> GetHits { get; set; }
        public List<int> GetMisses { get; set; }
        public List<int> IncrHits { get; set; }
        public List<int> IncrMisses { get; set; }
        public List<int> MemUsed { get; set; }
        public List<int> Misses { get; set; }
        public List<int> Ops { get; set; }
        public List<object> Timestamp { get; set; }
        public List<int> VbActiveEject { get; set; }
        public List<int> VbActiveItmMemory { get; set; }
        public List<int> VbActiveMetaDataMemory { get; set; }
        public List<int> VbActiveNum { get; set; }
        public List<int> VbActiveNumNonResident { get; set; }
        public List<int> VbActiveOpsCreate { get; set; }
        public List<int> VbActiveOpsUpdate { get; set; }
        public List<int> VbActiveQueueAge { get; set; }
        public List<int> VbActiveQueueDrain { get; set; }
        public List<int> VbActiveQueueFill { get; set; }
        public List<int> VbActiveQueueSize { get; set; }
        public List<int> VbPendingCurrItems { get; set; }
        public List<int> VbPendingEject { get; set; }
        public List<int> VbPendingItmMemory { get; set; }
        public List<int> VbPendingMetaDataMemory { get; set; }
        public List<int> VbPendingNum { get; set; }
        public List<int> VbPendingNumNonResident { get; set; }
        public List<int> VbPendingOpsCreate { get; set; }
        public List<int> VbPendingOpsUpdate { get; set; }
        public List<int> VbPendingQueueAge { get; set; }
        public List<int> VbPendingQueueDrain { get; set; }
        public List<int> VbPendingQueueFill { get; set; }
        public List<int> VbPendingQueueSize { get; set; }
        public List<int> VbReplicaCurrItems { get; set; }
        public List<int> VbReplicaEject { get; set; }
        public List<int> VbReplicaItmMemory { get; set; }
        public List<int> VbReplicaMetaDataMemory { get; set; }
        public List<int> VbReplicaNum { get; set; }
        public List<int> VbReplicaNumNonResident { get; set; }
        public List<int> VbReplicaOpsCreate { get; set; }
        public List<int> VbReplicaOpsUpdate { get; set; }
        public List<int> VbReplicaQueueAge { get; set; }
        public List<int> VbReplicaQueueDrain { get; set; }
        public List<int> VbReplicaQueueFill { get; set; }
        public List<int> VbReplicaQueueSize { get; set; }
        public List<int> VbTotalQueueAge { get; set; }
        public List<int> XdcOps { get; set; }
        public List<int> CpuIdleMs { get; set; }
        public List<int> CpuLocalMs { get; set; }
        public List<double> CpuUtilizationRate { get; set; }
        public List<int> HibernatedRequests { get; set; }
        public List<int> HibernatedWaked { get; set; }
        public List<object> MemActualFree { get; set; }
        public List<object> MemActualUsed { get; set; }
        public List<object> MemFree { get; set; }
        public List<object> MemTotal { get; set; }
        public List<object> MemUsedSys { get; set; }
        public List<int> RestRequests { get; set; }
        public List<object> SwapTotal { get; set; }
        public List<object> SwapUsed { get; set; }
    }
}